### ISSUE TITLE
lab01 tracker

### ISSUE THREAD

**Issue by jjdredd** [jjdredd/MATH201UofA#1]
- [x] Typo, last example
- [x] More explanation for integrating factor
- [x] More examples (exact, non exact, bernoulli)
